name: Invincible_Spawners
main: com.anomalytea.InvincibleSpawners.InvincibleSpawners
version: 1.0.0
api-version: 1.13
commands:
  invinciblespawners:
    description: Reload the Invincible Spawners configuration file without restarting the server.
    usage: /invinciblespawners reload
